#ifndef __COMPASS_REG_H__
#define __COMPASS_REG_H__

#define	CONFIGURATION_REGISTER_A	0x00
#define CONFIGURATION_REGISTER_B	0x01
#define MODE_REGISTER				0x02
#define DATA_OUTPUT_X_MSB_REGISTER	0x03
#define DATA_OUTPUT_X_LSB_REGISTER	0x04
#define DATA_OUTPUT_Z_MSB_REGISTER	0x05
#define DATA_OUTPUT_Z_LSB_REGISTER	0x06
#define DATA_OUTPUT_Y_MSB_REGISTER	0x07
#define DATA_OUTPUT_Y_LSB_REGISTER	0x08
#define STATUS_REGISTER				0x09
#define IDENTIFICATION_REGISTER_A	0x0A
#define IDENTIFICATION_REGISTER_B	0x0B
#define IDENTIFICATION_REGISTER_C	0x0C

#endif
